version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "04:30"
      timezone: "Europe/Amsterdam"
    ignore:
      - dependency-name: "Microsoft.*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: docker
    directory: "/UvA.Workflow.Api"
    schedule:
      interval: daily
      time: "04:30"
      timezone: "Europe/Amsterdam"
