using System.Text.Json;
using UvA.Workflow.Expressions;
using UvA.Workflow.WorkflowModel;
using UvA.Workflow.WorkflowModel.Conditions;

namespace UvA.Workflow.Submissions;

public class DummyAnswerGenerator
{
    private static readonly Random Random = new Random();

    private const string DummyStringValue =
        "This is test data generated by the admin fill action. It is not a real user submission.";

    public JsonElement? Generate(PropertyDefinition question, QuestionStatus status, DateTime? lastUpdated = null)
    {
        if (!question.IsArray) return GenerateSingleValue(question, status, lastUpdated);

        var items = new List<JsonElement>();
        for (var i = 0; i < Random.Next(1, 3); i++)
        {
            var single = GenerateSingleValue(question, status, lastUpdated);
            if (single != null)
                items.Add(single.Value);
        }

        return items.Count == 0 ? null : JsonSerializer.SerializeToElement(items);
    }

    private static JsonElement? GenerateSingleValue(PropertyDefinition question, QuestionStatus status,
        DateTime? lastUpdated = null)
    {
        var constraints = ExtractConstraints(question.Validation);
        var startDate = lastUpdated ?? DateTime.Now;

        return question.DataType switch
        {
            DataType.String => JsonSerializer.SerializeToElement(constraints.MaxLength.HasValue
                ? DummyStringValue[..constraints.MaxLength.Value]
                : DummyStringValue),
            DataType.Int => JsonSerializer.SerializeToElement(
                Random.Next((int)(constraints.Min ?? 1), (int)(constraints.Max ?? 10))),
            DataType.Double => JsonSerializer.SerializeToElement(
                (constraints.Min ?? 0) + Random.NextDouble() * ((constraints.Max ?? 10) - (constraints.Min ?? 0))),
            DataType.Boolean => JsonSerializer.SerializeToElement(Random.NextDouble() > 0.5),
            DataType.Currency => JsonSerializer.SerializeToElement(new
                { currency = "EUR", amount = Random.Next((int)(constraints.Min ?? 1), (int)(constraints.Max ?? 100)) }),
            DataType.Choice when status.Choices?.Length > 0
                => JsonSerializer.SerializeToElement(status.Choices[Random.Next(0, status.Choices.Length)]),
            DataType.DateTime or DataType.Date
                => JsonSerializer.SerializeToElement(startDate.AddDays(Random.Next(2, 30)).ToString("o")),
            _ => null
        };
    }

    internal record ValidationConstraints(double? Min, double? Max, int? MaxLength)
    {
        public static readonly ValidationConstraints None = new(null, null, null);
    };

    internal static ValidationConstraints ExtractConstraints(Condition? validation)
    {
        if (validation == null) return ValidationConstraints.None;

        return validation.Part switch
        {
            Value v when !validation.Not => ExtractFromValue(v),
            Logical { Operator: LogicalOperator.And } l => ExtractFromLogical(l),
            _ => ValidationConstraints.None
        };
    }

    internal static ValidationConstraints ExtractFromValue(Value v)
    {
        var greaterThan = TryGetLiteralNumber(v.GreaterThan);
        var greaterThanOrEqual = TryGetLiteralNumber(v.GreaterThanOrEqual);
        var lessThan = TryGetLiteralNumber(v.LessThan);

        double? min = greaterThan.HasValue ? greaterThan + 1 : greaterThanOrEqual;
        double? max = lessThan;

        return new ValidationConstraints(min, max, v.MaxLength);
    }

    internal static ValidationConstraints ExtractFromLogical(Logical logical)
    {
        double? min = null, max = null;
        int? maxLen = null;
        foreach (var child in logical.Children)
        {
            var c = ExtractConstraints(child);
            if (c.Min.HasValue) min = min == null ? c.Min : Math.Max(min.Value, c.Min.Value);
            if (c.Max.HasValue) max = max == null ? c.Max : Math.Min(max.Value, c.Max.Value);
            if (c.MaxLength.HasValue) maxLen = maxLen == null ? c.MaxLength : Math.Min(maxLen.Value, c.MaxLength.Value);
        }

        return new ValidationConstraints(min, max, maxLen);
    }

    internal static double? TryGetLiteralNumber(string? exprString)
        => ExpressionParser.Parse(exprString) switch
        {
            Number(var n) => (double)n,
            _ => null
        };
}