using System.Text.Json;
using UvA.Workflow.WorkflowModel;

namespace UvA.Workflow.Submissions;

public class FakeAnswerGenerator
{
    private static readonly Random Random = new Random();

    public JsonElement? Generate(PropertyDefinition question, QuestionStatus status)
    {
        if (!question.IsArray) return GenerateSingleValue(question, status);

        var items = new List<JsonElement>();
        for (var i = 0; i < Random.Next(1, 3); i++)
        {
            var single = GenerateSingleValue(question, status);
            if (single != null)
                items.Add(single.Value);
        }

        return items.Count == 0 ? null : JsonSerializer.SerializeToElement(items);
    }

    private static JsonElement? GenerateSingleValue(PropertyDefinition question, QuestionStatus status)
    {
        var fakeStringValue = new BilingualString(
            "This is test data generated by the admin fill action. It is not a real user submission.",
            "Dit zijn testgegevens die gegenereerd zijn door de invulactie van de beheerder. Het betreft geen echte gebruikersinzending.");

        return question.DataType switch
        {
            DataType.String => JsonSerializer.SerializeToElement(fakeStringValue.En),
            DataType.LocalString => JsonSerializer.SerializeToElement(fakeStringValue),
            DataType.Int => JsonSerializer.SerializeToElement(Random.Next(1, 10)),
            DataType.Double => JsonSerializer.SerializeToElement(Random.NextDouble() * 10),
            DataType.Boolean => JsonSerializer.SerializeToElement(Random.NextDouble() > 0.5),
            DataType.Currency => JsonSerializer.SerializeToElement(new
                { currency = "EUR", amount = Random.Next(1, 100) }),
            DataType.Choice when status.Choices?.Length > 0
                => JsonSerializer.SerializeToElement(status.Choices[Random.Next(0, status.Choices.Length)]),
            DataType.DateTime or DataType.Date
                => JsonSerializer.SerializeToElement(DateTime.Now.AddDays(Random.Next(2, 30)).ToString("o")),
            _ => null
        };
    }
}