apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-api-config
  namespace: "{{ .Release.Namespace }}"
data:
  DOTNET_ENVIRONMENT: "{{ .Values.environment }}"
  Serilog__MinimumLevel__Override__Uva.DataNose: "{{ .Values.logLevel }}"